### PR TITLE
Modernize all the things

### LINKED ISSUE #85: warning : code deprecated  when running app
When running example it throws below warning

```
Your Flutter application is created using an older version of the Android
embedding. It's being deprecated in favor of Android embedding v2. Follow the
steps at
```

### LINKED ISSUE #90: Support for null-safety?
Hi! First of all, thank you for your work and time creating this package, is amazing and help me a lot of times!!

There are any plan to migrate this package to null-safety? I think this is a package that another packages depends on, so there are a roadmap to be migrated?

Thank you!

### PR DESCRIPTION
**Pull request by hacker1024**
This PR contains a slew of changes:

* Migrate to null safety (resolves #90)
* Migrate to a federated plugin architecture (paves the way for #51)
* Migrate to v2 Android embedding APIs (resolves #85)
* Use more effective Dart guidelines in the example

As a part of this, it's worth noting that I removed the exception documentation in a few functions.
The exceptions documented should never be thrown by this plugin unless there's a bug; developers should not have to handle them.

### CODE REVIEW

**Comment by hacker1024** [comment]
This PR can supersede #69 because:
1. It supports null safety.
2. Platform-independent code like the URI stream is in the right spot - in #69, it's in the platform interface instead of the main plugin, which is incorrect.

**Comment by miDeb** [comment]
@avioli may I ask if you plan on merging this pr soon? FYI, if you don't want to mantain this package anymore you can also transfer ownership to [fluttercommunity](https://github.com/fluttercommunity/transfer-guide).

**Comment by avioli** [comment]
Thank you @hacker1024

**Comment by espresso3389** [comment]
Could you please tell me when do you release the new plugin version that contains the PR?

**Comment by IchordeDionysos** [comment]
@avioli there is no new release yet with the null-safety features ☺️

Could you publish a release to pub.dev? Would be really awesome 😍

**Pull request merged**
