### PR TITLE
Update getInitialLink() method call logic [Android only]

### PR DESCRIPTION
**Pull request by Vizhan**
@avioli 
On Android, there is an "issue" where the getInitialLink() method returns data multiple times. One way to produce this is:

* Open an application within a link (cold start)
* Close application by the pressing system back
* Open the Recents screen (aka recent task/app list) and go back to the application

This is happening when the application starts up again. However, when processing the intent it should check to make sure that the app isn't launched via the Recents screen. This PR as this guard in to prevent the "issue" from happening (do not return data to MethodChannel.Result when getInitialLink() called if application resuming from Recents screen).

### CODE REVIEW

**Comment by Vizhan** [comment]
@avioli 
Related issue https://github.com/avioli/uni_links/issues/83

**Comment by maheshmnj** [comment]
@avioli could you please review this PR

**Comment by avioli** [comment]
@Vizhan Does a launch from the Recents screen launch a new instance of the app or it resumes a backgrounded instance?

**Comment by avioli** [comment]
I'm sorry to say, but I don't have any time to maintain this package, so it is now marked as discontinued and `app_links` recommended replacement.

**Pull request closed without merging**
