### PR TITLE
Web support

### LINKED ISSUE #51: Flutter Web
We are using flutter web, desktop and mobile.

Has anyone gotten this to work with Flutter web ?

### PR DESCRIPTION
**Pull request by hacker1024**
This PR depends on #92, which should be merged first.
This resolves #51.

As the URL cannot be changed in Web apps by an external process without restarting the app, attempting to use the stream APIs will result in an `UnsupportedError`.

### CODE REVIEW

**Comment by Ahmadre** [comment]
@avioli

**Comment by psrcek** [comment]
@avioli

**Comment by avioli** [comment]
Thank you @hacker1024

**Comment by alihabbash** [comment]
Is the package now supporting flutter web?

**Comment by kiaxseventh** [comment]
> Is the package now supporting flutter web?

@avioli  please answer this question

**Comment by daraul** [comment]
I don't think it does. I'm still getting the unsupported error.

**Comment by raviganwal** [comment]
I am getting below error 

Error: Unsupported operation: As the Web URL cannot be changed without restarting the application, link streams are unimplemented on this platform.

**Comment by luisburgos** [comment]
I'm getting the same as @raviganwal, were you able to solve it?

**Comment by gerardsimons** [comment]
Web support just means throwing an error that says it's not supported? That seems rather Kafkaesque :)

**Pull request merged**
